name: Merge

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  oss_scorecard:
    uses: ./.github/workflows/scorecard.yaml

    permissions:
      contents: read
      security-events: write
      id-token: write

  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@51ee8ae2605bd5ce1cfdcc5938684908f1cd9f69 # v3.7.9
        with:
          release-type: simple
          command: github-release
  release-pr:
    runs-on: ubuntu-latest

    needs:
      - release

    permissions:
      contents: write
      pull-requests: write

    steps:
      - id: get_token
        uses: tibdex/github-app-token@0d49dd721133f900ebd5e0dff2810704e8defbc6 # v1.8.2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - uses: google-github-actions/release-please-action@51ee8ae2605bd5ce1cfdcc5938684908f1cd9f69 # v3.7.9
        with:
          token: ${{ steps.get_token.outputs.token }}
          release-type: simple
          fork: true
          command: release-pr
